kleros/kleros-v2

CHANGELOG.md
contracts/src/arbitration/ArbitrableExample.sol
contracts/src/arbitration/CentralizedArbitrator.sol
contracts/src/arbitration/IArbitrable.sol
contracts/src/arbitration/IArbitrator.sol

The document describing the updated standard https://docs.google.com/document/d/1VIBspauNpw7A8ZeHaSXN2t4RLyGdtognpZMvSk1cJPE/edit

feat(Arbitration): standard update

---

contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol

feat(DisputeKit): change RNG for governor only

---

contracts/src/arbitration/IDisputeKit.sol
contracts/src/arbitration/KlerosCore.sol
contracts/src/arbitration/dispute-kits/BaseDisputeKit.sol
contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol

feat(DisputeKit): Dispute Kits abstraction for interfacing with KlerosCore

---

contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol
contracts/src/evidence/EvidenceModule.sol
contracts/src/evidence/IEvidence.sol
contracts/src/evidence/IMetaEvidence.sol
contracts/src/evidence/ModeratedEvidenceModule.sol
contracts/src/gateway/interfaces/IHomeGateway.sol

Required splitting the IEvidence interface into 2: the MetaEvidence and Dispute events have been moved to an IMetaEvidence interface which extends IEvidence. Because IMetaEvidence is relevant only to the Arbitrable side but not IEvidence.
Resolves #46

feat(Evidence): evidence submission from the arbitration side

---

contracts/deploy/02-home-chain.ts
contracts/src/bridge/FastBridgeReceiverOnEthereum.sol
contracts/src/bridge/FastBridgeSenderToEthereum.sol
contracts/src/bridge/SafeBridgeReceiverOnEthereum.sol
contracts/src/bridge/SafeBridgeSenderToEthereum.sol
contracts/src/bridge/interfaces/IFastBridgeReceiver.sol
contracts/src/bridge/interfaces/IFastBridgeSender.sol

feat: Fast Bridge unhappy path

---

contracts/src/arbitration/IDisputeKit.sol
contracts/src/arbitration/KlerosCore.sol
contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol

feat: Dispute Kit Forest

---

contracts/src/bridge/merkle/MerkleProof.sol
contracts/src/bridge/merkle/MerkleTreeHistory.sol
contracts/test/bridge/merkle/MerkleTree.ts
contracts/test/bridge/merkle/index.ts

Differentiate leaves from interior nodes with different hash functions to prevent 2nd order pre-image attack.
> https://flawed.net.nz/2018/02/21/attacking-merkle-trees-with-a-second-preimage-attack/
This commit was supposed to have been included in the original PR.

fix: sha256 leaves to avoid 2nd pre-image attack

---

.gitignore
contracts/deploy/00-home-chain-arbitration.ts
contracts/deploy/01-foreign-chain.ts
contracts/deploy/02-home-chain.ts
contracts/src/bridge/mock/ArbSysMock.sol
contracts/src/bridge/mock/BridgeMock.sol
contracts/src/bridge/mock/FastBridgeSenderToEthereumMock.sol
contracts/src/bridge/mock/InboxMock.sol
contracts/src/bridge/mock/OutboxMock.sol
contracts/test/pre-alpha1/index.ts

Added Mock contracts for the bridge. 
Tests for following:
Honest Claim - No Challenge
Honest Chaim - Dishonest Challenger
Dishonest Claim - Honest Challenger

test: added bridge-tests for cases

---

contracts/deploy/00-home-chain-arbitration.ts
contracts/scripts/changeRng.ts
contracts/src/rng/IncrementalNG.sol
contracts/test/pre-alpha1/index.ts
contracts/test/rng/index.ts

fixed the IncrementalNG to start from a non-zero value, fixed the skipped tests

Fixed the IncrementalNG and skipped tests

---

.lintstagedrc.json
.vscode/settings.json
contracts/.eslintrc.js
contracts/tsconfig.json
package.json
yarn.lock

Typescript files were not linted by the pre-commit hook.
Two major changes:
- VS Code is going to use the top-level .prettierrc.json so it may affect the `web` and `subgraph` packages.
- The precommit hook does not run `eslint` anymore for .js files, only `prettier`.
What do you think? @alcercu @AndreiMVP

chore: fixed the linters configuration

---

contracts/src/arbitration/KlerosCore.sol

Feat(contracts): Add court and disputeKit events to ease subgraph indexing

---

contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol

Removes validations from `castCommit` function to allow submitting votes multiple times overriding the previous ones as long as the current period is `Commit`.
This also has the positive side effect of making the `castCommit` function cheaper.
This PR is the implementation for issue #182.

feat: allow overriding a vote commitment

---

contracts/package.json
contracts/src/arbitration/KlerosCore.sol
contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol

by shrinking require strings, by relying on generated getters, by consolidating some getters.
Blocks #202

refactor: finally KlerosCore is now below 24KB

---

contracts/src/arbitration/KlerosCore.sol
contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol

Fixes 3 separate bugs:
1. VoteID desync in `Draw `event. Previously voteID was tied to `i` which was incorrect, since with this approach if you call `draw() `several times the event can emit the same voteID for the different jurors.
2. In `appeal()` the court used an ID of a dispute kit for some reason
3. If minStake was increased the jurors with the stake lower than minStake could still be drawn #295

fix(Arbitration): small bug fixes

---

subgraph/schema.graphql
subgraph/src/KlerosCore.ts

Add fields to the court entity needed to populate the UI.

Feat(subgraph): Add court info

---

contracts/src/arbitration/IArbitrator.sol
contracts/src/arbitration/KlerosCore.sol
contracts/test/integration/index.ts

To make indexing more convenient

Arbitrator ruling event

---

web/src/consts/community-elements.tsx

close #648
i have put all the links but only 2 left as I have not found the links one is "join the community calls" and cooperative kleros.

fix(web): links to socials

---

web/src/context/Web3Provider.tsx
web/src/hooks/queries/useEvidenceGroup.ts
web/src/hooks/queries/usePNKBalance.ts

useEvidenceGroup, usePnkBalance hooks migration to viem/wagmi

refactor: migrate hooks to viem/wagmi

---

web/src/pages/Cases/CaseDetails/Appeal/Classic/Fund.tsx
web/src/pages/Cases/CaseDetails/Evidence/SubmitEvidenceModal.tsx
web/src/pages/Cases/CaseDetails/Voting/Binary.tsx
web/src/pages/Courts/CourtDetails/StakePanel/InputDisplay.tsx
web/src/pages/Courts/CourtDetails/StakePanel/StakeWithdrawButton.tsx
web/src/utils/wrapWithToast.ts

upload write functions to viem

fix: write functions to viem

---

web/src/utils/uploadFormDataToIPFS.ts

Fixes #920 
No bug, warning because the promise constructor was returning another promise (`fetch`), instead of returning `void`.
This can be fixed by just changing
`new Promise((resolve, reject) => fetch(...))` to
`new Promise((resolve, reject) => { fetch(...) })`
but we don't necessarily need another new promise, since `fetch` already returns a promise.
Here, it is semantically preferable to throw an `Error` type, so type annotations are also updated accordingly.

chore: fix linter error

---

contracts/src/arbitration/KlerosCore.sol
contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
contracts/src/arbitration/dispute-kits/DisputeKitSybilResistant.sol
contracts/src/arbitration/interfaces/IArbitratorV2.sol
contracts/src/arbitration/interfaces/IDisputeKit.sol
contracts/src/gateway/interfaces/IForeignGateway.sol

```solidity
event NewCurrencyRate(IERC20 indexed _feeToken, uint64 _rateInEth, uint8 _rateDecimals);
```
**Before**
```solidity
Justification(_coreDisputeID, _juror, _choice, _justification);
CommitCast(_coreDisputeID, _voteIDs, _commit);
```
**After**
```solidity
VoteCast(_coreDisputeID, _juror, _voteIDs, _choice, _justification);
CommitCast(_coreDisputeID, _juror, _voteIDs, _commit);
```
**Changes**
- Justification => VoteCast
- Adding _voteIDs to the vote event
- Adding _juror to the commit event
**Rationale**
- Consistency
- Enables a more connected subgraph as right now there is no direct  connection between voteID and justification
- Deploy the new contracts
- Update the subgraph
- Update the frontend

Refactor: events for voting, commitment and currency rate changes

---

web/src/components/Verdict/DisputeTimeline.tsx
web/src/components/Verdict/FinalDecision.tsx
web/src/pages/Cases/CaseDetails/Voting/VotingHistory.tsx
web/src/pages/Cases/CaseDetails/Voting/index.tsx

Fixes #1085 and other edge cases with disputeTemplate

fix: voting-results-and-display

---

web/src/components/CasesDisplay/Stats.tsx
web/src/hooks/queries/useAllCasesQuery.ts

feat(web): dynamic-values-in-cases-page

---

web/.gitignore
web/package.json
web/scripts/gitInfo.js
web/scripts/runEnv.sh
web/src/app.tsx
web/src/consts/index.ts
web/src/hooks/queries/usePhase.ts
web/src/index.tsx
web/src/layout/Footer/index.tsx
web/src/layout/Header/navbar/Debug.tsx
web/src/layout/Header/navbar/index.tsx
web/src/utils/sentry.ts

Debug info: Sentry instrumentation, release information, phase
